export const FETCH_RECENT = 'FETCH_RECENT';
export const FETCH_RECENT_SERVER = 'FETCH_RECENT_SERVER';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const OPEN_AND_PLAY_GLOBAL = 'OPEN_AND_PLAY_GLOBAL';
export const PAUSE_GLOBAL = 'PAUSE_GLOBAL';
export const CHANGE = 'CHANGE';
export const PLAY_GLOBAL = 'PLAY_GLOBAL';
export const HIDE_GLOBAL = 'HIDE_GLOBAL';
export const REVERSE_GLOBAL = 'REVERSE_GLOBAL';
export const CHANGE_GLOBAL = 'CHANGE_GLOBAL';
export const GLOBAL_VOLUME = 'GLOBAL_VOLUME';
export const SIGN_IN = 'SIGN_IN';
export const GLOBAL_HIDDEN_CLOSED = 'GLOBAL_HIDDEN_CLOSED';
export const PLAY = 'PLAY';
export const PAUSE = 'PAUSE';
export const SEEK = 'SEEK';
export const RESET_PROGRESS = 'RESET_PROGRESS';
export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SERVER = 'FETCH_USER_SERVER';
export const SET_INDEX_RECENT = 'SET_CUR_INDEX_RECENT_LIST';
export const SET_MSG = 'SET_MSG';
export const REMOVE_MSG = 'REMOVE_MSG';
export const RESET_MSG = 'RESET_MSG';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const RESET_GLOBAL_SOUND = 'RESET_GLOBAL_SOUND';
export const PLAY_SET_GLOBAL_SOUND = 'PLAY_SET_GLOBAL_SOUND';
export const SET_UPLOAD_SOUND = 'SET_UPLOAD_SOUND';
export const SET_UPLOAD_BUFFER = 'SET_UPLOAD_BUFFER';
export const SAVE_UPLOAD_FORM = 'SAVE_UPLOAD_FORM';
export const SET_FX_PLAY = 'SET_FX_PLAY';
export const SET_FX_PAUSE = 'SET_FX_PAUSE';
export const SET_FX_DIST = 'SET_FX_DIST';
export const SAVE_FX_BUFF = 'SAVE_FX_BUFF';
export const MUTE_GLOBAL = 'MUTE_GLOBAL';
export const END_GLOBAL_SOUND = 'END_GLOBAL_SOUND';
export const START_ACTION = 'START_ACTION';
export const SAVE_BROWSE = 'SAVE_BROWSE';
export const STOP_ACTION = 'STOP_ACTION';
export const REFRESH_ACTION_START = 'REFRESH_ACTION_START';
export const REFRESH_ACTION_STOP = 'REFRESH_ACTION_STOP';
export const SAVE_BROWSE_TAGS = 'SAVE_BROWSE_TAGS';
export const SAVE_XTRA_BROWSE = 'SAVE_XTRA_BROWSE';
export const SET_GLOBAL_SOUND = 'SET_GLOBAL_SOUND';
export const SAVE_1_UPLOAD_SOUND_LIST = 'SAVE_1_UPLOAD_SOUND_LIST';
export const SET_UPLOAD_SOUND_LIST_INFO = 'SET_UPLOAD_SOUND_LIST_INFO';
export const SET_UPLOAD_SOUND_LIST_SINGLE_NAME = 'SET_UPLOAD_SOUND_LIST_SINGLE_NAME';
export const CHANGE_1_SOUND_LIST_CATEGORY = 'CHANGE_1_SOUND_LIST_CATEGORY';
export const CHANGE_1_SOUND_LIST_GENRE = 'CHANGE_1_SOUND_LIST_GENRE';
export const CHANGE_1_SOUND_LIST_TAGS = 'CHANGE_1_SOUND_LIST_TAGS';








